obj:
  # _target_: models.backbones.csn.csn_temporal_no_head # backbone 고치기
  _target_: models.backbones.vivit_model3.ViViTBackbone # backbone 고치기
  # image_size: 112
  # patch_size: 16
  # num_classes: 2 
  # num_frames=: 5
  t: 25
  h: 112
  w: 112
  patch_t: 1
  patch_h: 28
  patch_w: 28
  num_classes: 500
  dim: 512
  depth: 6
  heads: 10
  mlp_dim: 8
  model: 3
output_dim: 512